### ISSUE TITLE
typo in documentation for sample "Modern Team Sites" customizer

### ISSUE THREAD

**Issue by grahampasmurf** [SharePoint/sp-dev-fx-extensions#111]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The instructions on one of the samples should be this:
gulp serve --nobrowser

but there is a typo that will confuse those not familiar with gulp commands.

#### Observed Behavior
Running "gulp server --nobrowser" results in the error, 
"Task 'server' is not in your gulpfile"

#### Steps to Reproduce
Go to the page for sample for "[Modern Team Sites (Office Groups) Navigation Application Customizer](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-application-office-groups-nav)" and follow instructions.

After instruction "npm i -g gulp" is the line "gulp server --nobrowser" that produces the error.

**Comment by VesaJuvonen** [comment]
Fixed to readme. Thx for reporting.
