### ISSUE TITLE
Tenant Global Nav Bar overflow menu not working

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-dev-fx-extensions#118]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When overflow menu is used the links no longer work.

#### Observed Behavior
When menu overflows the menu items are rendered but not clickable. How do i fix this?

#### Steps to Reproduce
Make screen small to cause overflow

**Comment by varun5585** [comment]
Comment the itemType in the projectMenuItem function would fix the overflow issue

` private projectMenuItem(menuItem: SPTermStore.ISPTermObject, itemType: ContextualMenuItemType) : IContextualMenuItem {
      return({
        key: menuItem.identity,
        name: menuItem.name,
        //itemType: itemType,
        iconProps:{ iconName: (menuItem.localCustomProperties.iconName != undefined ? menuItem.localCustomProperties.iconName : null)},
        href: menuItem.terms.length == 0 ?
            (menuItem.localCustomProperties["_Sys_Nav_SimpleLinkUrl"] != undefined ?
                menuItem.localCustomProperties["_Sys_Nav_SimpleLinkUrl"]
                : null)
            : null,
        subMenuProps: menuItem.terms.length > 0 ? 
            { items : menuItem.terms.map((i) => { return(this.projectMenuItem(i, ContextualMenuItemType.Normal)); }) } 
            : null,
        isSubMenu: itemType != ContextualMenuItemType.Header,
      });
  }`

**Comment by harshdamaniahd** [comment]
This works , but we reduce the size of page i.e window , the top nav bar is hidden

**Comment by varun5585** [comment]
I noticed this to be a office UI fabric command bar issue. Although, we were not able to replicate this on actual mobile devices or tablets.
