### ISSUE TITLE
Command set extension only showing up when gulp serve is running

### ISSUE THREAD

**Issue by arunvinoth** [SharePoint/sp-dev-fx-extensions#124]
## Category

- [x] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior
Am following [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api), and developed a command set. Deployed in my site collection, and able to see the commandset for my List. Step 6 says I have to run `gulp serve --nobrowser`  & its working only when the above command is running. I wanted this to work even when powershell is not running.

## Observed Behavior
Step 6 says I have to run `gulp serve --nobrowser`  & its working only when the above command is running.

## Steps to Reproduce
Deploy the command set in site collection following the exact steps in above said article. And test it.

**Comment by arunvinoth** [comment]
I guess I need to follow [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions#enable-the-cdn-in-your-office-365-tenant) once the steps are completed, it may work as expected.. May be link at the bottom of this article will help us to see the holistic picture.

**Comment by luismanez** [comment]
I think you also will need to have a look into this one:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint

basically you need to Deploy your spfx extension into SP, that means not only what you're saying in your last link, but also to register the ListView command set to a SP List (in my link, also you will need to set the proper "location": https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api#more-details-about-the-url-query-parameters)

**Comment by VesaJuvonen** [comment]
As this seems to be a generic issue, would request to reopen it at the sp-dev-docs, so that we get it under the official engineering process, if it's still an issue. This issue list ONLY for issues in the samples located in this repository as noted in the issue template instructions. We use http://aka.ms/spdev-issues as a centralized location for generic issues, which are also copied to our VSO for tracking. Thx.
