### ISSUE TITLE
Bind script suddenly stopped working

### ISSUE THREAD

**Issue by AlanMRichards** [SharePoint/sp-dev-fx-extensions#131]
- [x] Question
- [ ] Bug
- [ ] Enhancement

## Observed Behavior
Have installed the app to the SharePoint app catalog and it has been binding with no issues to site collection and today stopped working with the error:
The property 'ClientSideComponentId' cannot be found on this object. Verify that the property exists and can be set.

## Steps to Reproduce
Powershell open with admin rights
PnP-Connect with global admin account
run tenant customiser script

![2018-05-10_13-09-47](https://user-images.githubusercontent.com/39158651/39869200-9122c300-5454-11e8-9b27-a9238658ad5b.png)

**Comment by VesaJuvonen** [comment]
This seems to indicate that you are using an older version of the CSOM in your environment. The exact issue really depends also on what's included and executed in the TenantGlobalNvBarProvisionCustomizer.ps1 as the content of the PowerShell file is not shared. If you still have this issue, please open up a new issue at sp-dev-docs (http://aka.ms/spdev-issues) as this issue does not seem to be related on any of the issues in this repository.
