### ISSUE TITLE
ListView Command set visible on List and not on Document Library.

### ISSUE THREAD

**Issue by mubash7** [SharePoint/sp-dev-fx-extensions#133]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
For Listview Command set, if RegID is 101, the command set should be deployed in document library.

#### Observed Behavior
Command set visible in List and not on Document Library
[Elements.txt](https://github.com/SharePoint/sp-dev-docs/files/2011840/Elements.txt)
@VesaJuvonen 

#### Steps to Reproduce
Followed  instructions on MS tutorial:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

#### Submission Guidelines
I have read that changing the RegId fixes the issue but does not seems to be happening in my case.
https://github.com/SharePoint/sp-dev-docs/issues/1628

Thanks for your contribution! Sharing is caring.

**Comment by sanfo168** [comment]
It could be that your ClientSideComponentID does not have an ID associated with it.  Try going into your UpRevisionCommandSet.manifest.json file and use the ID from there as the ClientSideComponentID in the elements.xml.

Hope this helps!

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2009

**Comment by VesaJuvonen** [comment]
Moving to sp-dec-docs repository as this is a generic question, not specific for any sample in this repository.
