### ISSUE TITLE
Field customizer on classic site or page

### ISSUE THREAD

**Issue by markved** [SharePoint/sp-dev-fx-extensions#134]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Question: Does Field Customizer extension work on Classic site and page? I created a simple field extension to render HTML of field value but it doesn't seem to work.

The onRenderCell method includes this line of code:
event.domElement.innerHTML = `
    <a href='/sites/xxxxx/SitePages/ProjectDetails.aspx?ProjectID=${event.fieldValue}'>Details</a>`;

but it displays nothing on the view or on page with view web part.

Note: Not raising this as a bug as this could be as expected on classic site/page.

**Comment by lexschulz** [comment]
Hi Markved,
I think in your case you should use Client Side Rendering (CSR).

https://www.codeproject.com/Articles/620110/SharePoint-Client-Side-Rendering-List-Views

Hope this helps.

**Comment by VesaJuvonen** [comment]
Field customizers are not supported on classic experiences. Your option is to use CSR, like noted by @lexschulz.
