### ISSUE TITLE
react-application-tenant-global-navbar mobile view issue

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-extensions#135]
The above top navigation works perfectly fine in desktop view, but as soon as i change view to mobile it disappears.
Through Inspect Element , I find that it is hidden
@media screen and (max-width: 639px)
<style>…</style>
.SPPageChrome-app .ms-CommandBar .ms-CommandBarItem {
    display: none;
}
If i change this to display:inline .. it works.
But also gets applied to other elements on page

**Comment by sparkitect** [comment]
Add a rule to the app's specific CSS (in /src/extensions/tenantGlobalNavBar/AppCustomizer.module.scss on line 22).

BEFORE:
`
    .commandBar {
      width: 100%;
    }`

AFTER:
`
    .commandBar {
      width: 100%;
      display:inline;
    }`
