### ISSUE TITLE
Load SPFX webparts only after application customizer init method is completed ?

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-extensions#136]
I have some webparts who have dependency of data which is obtained from application customizer.
Is it possible to load webparts after application customizer

**Comment by VesaJuvonen** [comment]
There's no generic way to do this. You'd need to deal with this logic in your own JavaScript implementation. Notice also that as this is a generic question and not related on any of the issues in this repository, we would request to ask these kinds of questions at sp-dev-docs issue list - http://aka.ms/spdev-issues.
