### ISSUE TITLE
react-msal-bot simply not working

### ISSUE THREAD

**Issue by GodTigga** [SharePoint/sp-dev-fx-extensions#155]
Has anyone had success with the react-msal-bot? I've followed these instructions multiple times but the bot simply doesn't show up, the worst result I've received so far is site contents is blank when running my local gulp server (gulp serve --nobrowser)...am I missing something here?

**Comment by FranckyC** [comment]
Hi @GodTigga, sorry for late response. Can you give me some details about errors you get when setup the solution?

**Comment by FranckyC** [comment]
Maybe you can try this fix https://github.com/SharePoint/sp-dev-fx-extensions/issues/162 as well. Let me know.

**Comment by hugoabernier** [comment]
Hey @GodTigga did @FranckyC 's recommendation help you? 

I'll go ahead and close the issue. If you need more help, please don't hesitate to open a new issue.

Thanks @FranckyC  for your help with this!
