### ISSUE TITLE
Provision sharepoint assets with extensions?

### ISSUE THREAD

**Issue by zolem** [SharePoint/sp-dev-fx-extensions#158]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

Can you provision assets such as columns, content types, and lists with an spfx extension? All the tutorials and examples seem to only exist for spfx web parts and all my attempts at provisioning SharePoint assets with an extension have failed for me. I am wondering if it is just not a thing for extensions.

**Comment by zolem** [comment]
I have been trying to do it with a webpart and I am running into the same issue. Of course I don't really know what the issue is thanks to https://github.com/SharePoint/sp-dev-docs/issues/872#issuecomment-418906294

Hopefully some validation will occur at somepoint to help us provision things.

**Comment by VesaJuvonen** [comment]
As this is a generic question and not related on any sample in this repository, we will be closing this and we'll follow up on any submission in the sp-dev-docs repository, as noted in the issue template. To be able to investigate what goes wrong you should do the following:

- Submit new issue in the sp-dev-docs
- Add either correlation ID+tenant name or the solution as part of the issue - as with current details, there really is no way to identify what goes wrong
- If you don't see correlation ID, we'd need to see the solution to identify what goes wrong... as with currently provided details, there's really nothing we can work with
