### ISSUE TITLE
Calling REST Api with SPHtttpClient get 403

### ISSUE THREAD

**Issue by lazaki** [SharePoint/sp-dev-fx-extensions#16]
#### Category
- [ ] Question

I call the list api in my tenant with SPHttpClient, and get 403, also try to call same api using jQuery ger method wich work. 

Can you tell me the recommended way to REST call from the Shared Point Extension?

Thank you.

**Comment by waldekmastykarz** [comment]
The recommended way for calling SharePoint is by using the SPHttpClient. For non-SharePoint APIs you should use the HttpClient. If you use for example AngularJS, it comes with its own $http service that you can use instead.

**Comment by VesaJuvonen** [comment]
I'm assuming that @waldekmastykarz 's answer took care of this issue due no additional input. If that's not the case, please let us know. I'll close this one for now.
