### ISSUE TITLE
react-msal-bot - TypeError

### ISSUE THREAD

**Issue by omega1119** [SharePoint/sp-dev-fx-extensions#162]
Hi there,

I've followed all the instructions to deploy and run the chat bot, but when I try to run the app.js file I keep getting this error and I can't seem to figure it out:

const connector = new builder.ChatConnector({
                  ^

TypeError: builder.ChatConnector is not a constructor
    at Object.<anonymous> (D:\home\site\wwwroot\app.js:18:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Any help would be greatly appreciated.

Thanks!

**Comment by Tomatokun13** [comment]
Hi @omega1119 , did you copy/paste the right [package.json file ](https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/samples/react-msal-bot/bot/package.json)? 
If so, try to delete the node_modules folder and reinstall all the packages.

cc : @FranckyC

**Comment by omega1119** [comment]
Hi @Tomatokun13,

yes I've done that several times as well as the package-lock.json as well as getting latest of all the packages. This is my current package.json

{
  "name": "bot",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "botbuilder": "^4.0.6",
    "botbuilder-azure": "^4.0.6",
    "node-fetch": "^2.2.0",
    "restify": "^7.2.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node app.js"
  },
  "author": "",
  "license": "ISC"
} 

Thanks

**Comment by Tomatokun13** [comment]
Try this

{
  "name": "bot",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    **"botbuilder": "3.15.0",
    "botbuilder-azure": "^3.1.0",**
    "node-fetch": "2.1.2",
    "restify": "7.2.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node app.js"
  },
  "author": "",
  "license": "ISC"
}

**Comment by FranckyC** [comment]
Hi like @Tomatokun13  said, remove all "^" character before each package to install a fixed version. Then run a `npm i`. Don't forget to wipe your nodes_modules before.
