### ISSUE TITLE
react-mega-menu doesn't work in ie11 when deployed

### ISSUE THREAD

**Issue by SebastianLarsson** [SharePoint/sp-dev-fx-extensions#165]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

The extension working the same way deployed and run through the workbench

## Observed Behavior

react-mega-menu works in IE11 when tested in the workbench, but deployed on a site doesn't load any links.  

## Steps to Reproduce

Test react-mega-menu with the workbench and the test data it works in ie11. Bundle, ship, deploye (as sharepoint online hosted for cdn), it doesn't load any links when using ie11. It is just an empty page

**Comment by VelinGeorgiev** [comment]
@SebastianLarsson , I am sorry for the late response. The extension [requires a list to be created and populated with data](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-mega-menu#can-be-used-as-centralized-site-collection-mega-menu-as-well-as-standalone---per-sub-web) to display something when not in debug.

Have you created a list with at least one item inside? You can use PnP PowerShell or the PnP Office 365 CLI to provision the list if you do not want to use the feature xml in the sample.

I tested the latest updated sample and seems to be working form me in IE11 when I have list populated with data.
