### ISSUE TITLE
react-application-tenant-global-navbar gulp serve not working. Cannot find manifests.js

### ISSUE THREAD

**Issue by thomasberman** [SharePoint/sp-dev-fx-extensions#166]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Expected or Desired Behavior

When appending the query string to a SharePoint site, the react-application-tenant-global-navbar extension being served should render

## Observed Behavior

I receive an error that manifests.js is not accessible.

![image](https://user-images.githubusercontent.com/3643224/46206375-bbf92200-c31b-11e8-8986-67d9834181a6.png)

## Steps to Reproduce

- Clone this repository 
- `cd samples/react-application-tenant-global-navbar` 
- `npm i`
- `gulp serve --nobrowser`
- open a modern SharePoint site (communication site in my instance) append `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"b1efedb9-b371-4f5c-a90f-3742d1842cf3":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"TopMenuTermSet":"TenantGlobalNavBar","BottomMenuTermSet":"TenantGlobalFooterBar"}}}` to the URL

Node version is: 8.11.3

**Comment by kachihro** [comment]
I often get that - and it's due to either CHROME - or Kaspersky (AV block).

Can you browse to the file on it's own - in another tab :    https://localhost:4321/temp/manifests.js

**Comment by jonasesser** [comment]
I have the same error and in the command line the following error apears: 

Error: ENOENT: no such file or directory, stat 'C:\Data\Dev\SharePoint Online\react-application-tenant-global-navbar\dist\public\temp\manifests.js'

The path \dist\public\temp\workbench.htm does not exists. The correct path should be only \temp\manifests.js.

Any ideas what's going wrong here?

**Comment by jonasesser** [comment]
> I often get that - and it's due to either CHROME - or Kaspersky (AV block).
> 
> Can you browse to the file on it's own - in another tab : https://localhost:4321/temp/manifests.js

Same error by browse direct to https://localhost:5432/temp/manifest.js. The error disapears if I manuelly copy the temp folder to \dist\public\, but this couldn't be the solution and I ran directly into another error.

The serve.json of the repo looks like the following:

` {
"$schema": "https://dev.office.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "initialPage": "https://localhost:5432/workbench",
  "https": true,
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}`

I don't understand why @thomasberman tries to use port 4321, but maybe he changed the serve.json config!?

**Comment by hugoabernier** [comment]
@thomasberman did you ever resolve this issue?

I'll go ahead and close this due to the lack of activity, but feel free to re-open an issue if you still need help.
