### ISSUE TITLE
react-application-regions-footer - GeoGroups.xml  - "The provided template is not valid!" 

### ISSUE THREAD

**Issue by cloudedturtle** [SharePoint/sp-dev-fx-extensions#167]
## Category
- [x] Bug

## Expected or Desired Behavior
Executing the Import-PnPTermGroupFromXml should update/create a termset within the termstore with the information from the XML file. 

## Observed Behavior
When Attempting this PowerShell command using the data from the samples I get a message that states "The provided template is not valid!" 

```
Import-PnPTermGroupFromXml : The provided template is not valid!
At line:1 char:1
+ Import-PnPTermGroupFromXml -Path .\GeoGroups.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Import-PnPTermGroupFromXml], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Taxonomy.ImportTermGroupFromXml
```
## Steps to Reproduce
Clone the repo
from Powershell connect to SPO tenant using "Connect-PnPOnline" command
from PowerShell execute Import-PnPTermGroupFromXml (per readme instructions)

**Comment by hugoabernier** [comment]
Hey @cloudedturtle did @vtkachenko 's pull request ever solve your issue?

I'll go ahead and close this, but if you still need more help, please don't hesitate to open a new issue.

Thanks @vtkachenko for your help!
