### ISSUE TITLE
TypeScript error with SharePoint module in SPFx Extension 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-extensions#17]
#### Category
- [ ] Question

I am trying to connect to SharePoint term store using the JavaScript Object Model (JSOM) as explained [here](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom). But I am getting the below error: 

Any idea? 

Feature : SPFx Extension 

![image](https://user-images.githubusercontent.com/21008316/27502251-6e7c0f46-5838-11e7-87e4-9c0a26ea8a99.png)

**Comment by sprider** [comment]
@VesaJuvonen - Any suggestions?

**Comment by sprider** [comment]
@waldekmastykarz - Is this a bug?

**Comment by VesaJuvonen** [comment]
Hi Joseph, could you add these kind of potential issues in SPFx to sp-dev-docs repository issue list. We have dedicated MS engineers helping with questions there. Thx.

If issue is within a sample on specific Repo, then there, but this is potential issue in actual SPFx platform.

**Comment by sprider** [comment]
Sure, Vesa. 

Thank you.
