### ISSUE TITLE
Application Customizer suddenly stopped working on SitePages

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-extensions#171]
Application Customizer Suddenly stopped working on SitePages Page.
It was working on rest of modern page.
I tried deploying it to a new tenantt , it is working there as well

Error screen shot
![image](https://user-images.githubusercontent.com/11780473/47024901-e42db100-d162-11e8-9720-55390e14e882.png)

**Comment by waldekmastykarz** [comment]
What are you trying to get the domElement of?

**Comment by harshdamaniahd** [comment]
It is a react mega menu code, trying to top placeholder.
This same extension is getting loaded on Allitems.aspx,settings.aspx and other OOB pages.But not loading on SitePages Library Page.
Also if i refresh many times, sometimes the extension is loaded and sometimes it is not
![image](https://user-images.githubusercontent.com/11780473/47043650-697a8b00-d18e-11e8-9c3c-a74638d89e28.png)

**Comment by harshdamaniahd** [comment]
Just an update, I have not made any changes to my code today and now its working.
is something going on with SitePages in background ?

**Comment by VesaJuvonen** [comment]
There was a regression, which was then fixed. Thanks for following up on it to work now properly. Closing the issue.
