### ISSUE TITLE
Extension resources propagate to different site collection when navigating through hub site

### ISSUE THREAD

**Issue by jcosta33** [SharePoint/sp-dev-fx-extensions#174]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Observed Behavior

When navigating using the hub site navigation the page doesn't reload. If any extension is loaded on the page its resources are propagated to the navigated page, even if it's a different site collection that doesn't have this extension. ie: CSS form extension X designed to affect site collection X is going to affect site collection Y. 

## Steps to Reproduce

Load an SPFx Extension with some custom CSS, navigate using the hub navigation into a different site collection and see the CSS being propagated into the newly navigated site.

Thank you!

**Comment by jcosta33** [comment]
I'm temporarily forcing refresh when I detect a navigation of this kind. This is not an optimal solution, can I get an update this issue?

**Comment by hugoabernier** [comment]
Hey @jcosta33 did you ever solve this issue?

I'll close the issue due to the lack of activity, but feel free to open a new issue if you still need more help. Maybe we'll be able to get a fresh set of eyes on this.
