### ISSUE TITLE
react-msal-bot gulp bundle issue

### ISSUE THREAD

**Issue by omega1119** [SharePoint/sp-dev-fx-extensions#179]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I'm trying to package up the extension for deployment into the app catalog.

## Observed Behavior

When I run gulp bundle I get the following warning/error:

Warning - [webpack] 'dist':
./node_modules/adaptivecards/lib/adaptivecards.js
(Emitted value instead of an instance of Error) Cannot find source file '../src/adaptivecards.ts': Error: Can't resolve '../src/adaptivecards.ts' in 'C:/Users/name/Downloads/sp-dev-fx-extensions-master/samples/react-msal-bot/spfx/node_modules/adaptivecards/lib'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/adaptivecards.ts': Error: Can't resolve '../src/adaptivecards.ts' in 'C:/Users/name/Downloads/sp-dev-fx-extensions-master/samples/react-msal-bot/spfx/node_modules/adaptivecards/lib'

there are other errors along similar lines such as:

./node_modules/adaptivecards/lib/card-elements.js
(Emitted value instead of an instance of Error) Cannot find source file '../src/card-elements.ts': Error: Can't resolve '../src/card-elements.ts' in 'C:/Users/name/Downloads/sp-dev-fx-extensions-master/samples/react-msal-bot/spfx/node_modules/adaptivecards/lib'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/card-elements.ts': Error: Can't resolve '../src/card-elements.ts' in 'C:/Users/name/Downloads/sp-dev-fx-extensions-master/samples/react-msal-bot/spfx/node_modules/adaptivecards/lib'

## Steps to Reproduce

- get latest of https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-msal-bot
- go to the /spfx folder
- run the following:
- npm install
- gulp clean
- gulp build
- gulp bundle

- error message. I  originally got this error when I was updating my spfx extension to 1.6 and had all kinds of errors. So I got the original code from the repo and tried building from scratch and have been receiving these errors and I'm currently blocked by this issue.

Thanks,
Simon

**Comment by Ravi-Kulkarni** [comment]
I am also getting the same error,  any updates on the issue?

**Comment by hugoabernier** [comment]
Hey @omega1119 did you ever resolve this issue?

I'll go ahead and close the issue because it is a couple years old, but feel free to re-open it if you need more help.
