### ISSUE TITLE
How to configure ListViewCommandSet to be enabled ONLY when Folder selected?

### ISSUE THREAD

**Issue by harrychen1** [SharePoint/sp-dev-fx-extensions#232]
- [x] Question
- [ ] Bug
- [ ] Enhancement

Is there anyway to configure ListViewCommandSet to be enabled ONLY when Folder selected not item?

Thanks in advance for any suggestions!

**Comment by sudharsank** [comment]
Hi @harrychen1 
Using **event** param from the **onListViewUpdated** method, you can show or hide the command button based on the item selected is a folder or file. Please refer to the screenshot below.
![image](https://user-images.githubusercontent.com/10280385/79060615-cdb1d880-7cb9-11ea-890c-0aa5428ecba7.png)
In the above screenshot, I am using the **FSObjType** which is returned as a property of the selected item or file or folder. I am displaying the command button only when the selected item is a folder.

**_Happy Coding..._**

**Comment by hugoabernier** [comment]
@harrychen1, @sudharsank's approach is exactly the same approach I would have suggested.

I hope this takes care of your issue?

I'll go ahead and mark this issue as closed, but absolutely feel free to re-open it if you still need help with this.

Thanks @sudharsank for your help!
