### ISSUE TITLE
How to use UI fabric icons as icons for the spfx extension?

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-fx-extensions#253]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## How to use UI fabric icons for spfx extension?

I know we can add custom logo for the spfx extension from the manifest file like below

`"commands": {
    "DIRECTIONS": {
      "title": "Directions",
      "iconImageUrl": "icons/request.png"
    }
  }`

I want to know how to use the office UI fabric icons like we use in spfx.

**Comment by VesaJuvonen** [comment]
This is not currently supported. You can vote for the feature at following UserVoice entry - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/31781332-allow-to-use-office-ui-fabric-icons-and-other-font
