### ISSUE TITLE
Not able to run the sample code

### ISSUE THREAD

**Issue by v-jain** [SharePoint/sp-dev-fx-extensions#27]
#### Category
- [ ] Question

#### Observed Behavior

As mentioned to test extensions, we need to run npm install at tutorial directory. But there is no package.json file due to which unable to install modules.
When running [Field-Extension Tutorial](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/tutorials/field-extension) sample not able to see add any webpart option.

#### Steps to Reproduce
follow the link  [Field-Extension Tutorial](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/tutorials/field-extension) enter gulp serve.
![err](https://user-images.githubusercontent.com/30028922/27997779-21ae22ac-651d-11e7-90e8-50e4c2bdc5e7.png)

Thanks for your contribution! Sharing is caring.

**Comment by BassemNKhalil** [comment]
Looks like you're trying to test with the workbench. SharePoint Framework extensions are currently available from Office 365 developer tenants only and cannot be tested using the local workbench

[source](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/build-a-hello-world-extension)

**Comment by v-jain** [comment]
Thanks Bassem, I have tried with Office trial subscription for 1 month. It does not load load anything,
went through few url's got this guy also have the same issue as I have. 

####https://github.com/SharePoint/sp-dev-docs/issues/640

Is my subscription has anything to do with this ?

**Comment by BassemNKhalil** [comment]
Yes it does. You need a developer tenant not a production tenant. Trial
ones are production tenants and Microsoft hasn't rolled out the extensions
to that yet. You can use the following link (
https://dev.office.com/devprogram) to register for 1 year free developer
tenant.

**Comment by VesaJuvonen** [comment]
I'm assuming that @BassemNKhalil  took care of this (thx) and closing the issue for now. Let's continue discussion, if needed.
