### ISSUE TITLE
Looking for an Auto PDF Conveter which can be decalred in SharePoint Workflow 

### ISSUE THREAD

**Issue by tejasthite** [SharePoint/sp-dev-fx-extensions#276]
Dear All,

I am Looking for an Auto PDF Converter which can be declared in SharePoint Workflow "I have an Approval Workflow wherein I need to set up auto PDF Conveter if the condition is YES"

Any Help is Appreciated.

Thank you

**Comment by VesaJuvonen** [comment]
Closing as not an issue related on the samples in this repository.
