### ISSUE TITLE
SharePoint rendering blank page after deploying app customizer

### ISSUE THREAD

**Issue by manoj2784** [SharePoint/sp-dev-fx-extensions#281]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Thanks for the New Sample - js-application-intranet-searchbox, this works as expected, however in some cases it gives the following issue

## Observed Behavior

Thanks for this sample, it works perfectly fine. However, after adding this extension, intermittently we are getting blank page loads. On removing the externsion, the pages load correctly. Not sure what we are missing here. I'm sharing the http watch logs and console errors as well. Any help is much appreciated,

![](https://user-images.githubusercontent.com/32920340/72691842-7b5e9100-3b7c-11ea-9e1d-6e57d3fa632e.PNG)

Any idea what could be the issue here

Thanks for your contribution! Sharing is caring.

**Comment by ValerasNarbutas** [comment]
Hi @manoj2784 , 
could you check if new version added by @PrasadKasireddy fixed your issue?
