### ISSUE TITLE
Error when running extensions samples

### ISSUE THREAD

**Issue by shajivenugopal** [SharePoint/sp-dev-fx-extensions#29]
When running the extension samples for Application customizer.  I get the following error.  Error details: Error: Killswitches are not initialized. Killswitch requested: 19a3ca15-2aa2-4b0d-a563-4fbee7d77208 

I have tried the Hello World extensions and that was working previously, but now has stopped working.  Is this has anything to do with the extension being in dev preview?

Steps to Reproduce
- Clone the sample
- npm install
- gulp server --nobrowser
- Browse to the SharePoint site with the following query string ?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"<<your extension guid from manifest.json>>":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"testMessage":"Hello"}}}

**Comment by VesaJuvonen** [comment]
We have not changed the extension situation, but would double check that you are using developer tenant. It's important to use actual developer tenant, since using developer site collection in first release tenant is not enough making them work.

**Comment by VesaJuvonen** [comment]
Are you still having issues around the sample in developer tenant?

**Comment by VesaJuvonen** [comment]
Hi @shajivenugopal, closing this due no response within 10 days. Please reopen or submit a new one with additional details, if you are still having this issue.

**Comment by jcosta3394** [comment]
Hi @VesaJuvonen! I'm experiencing the same issue when running a vanilla SPFx Extension ever since the latest update of the framework (v1.4.1). I am unable to run a completely empty project.

**Comment by MNaujoks** [comment]
Hi @VesaJuvonen! I got this issue too, while trying to debug an SPFx Extension. 
I´m also using the most recent Version of the Framework (1.4.1).

**Comment by majidgorbani** [comment]
Hi,
same here "Killswitches are not initialized. Killswitch requested"

**Comment by VesaJuvonen** [comment]
@jcosta3394 - could you report this as an isolated issue and provide also the version details from your environment. OS and version details around node and npm. Thx.

**Comment by VesaJuvonen** [comment]
@MNaujoks  - could you report this as an isolated issue and provide also the version details from your environment. OS and version details around node and npm. Thx.

**Comment by VesaJuvonen** [comment]
@majidgorbani  - could you report this as an isolated issue and provide also the version details from your environment. OS and version details around node and npm. Thx.

**Comment by VesaJuvonen** [comment]
Please submit any generic SPFx issu to http://aka.ms/spdev-issues, so that we get it tracked using official channels. Thx. This issue list is for issues only on the samples in this repository. Thx.
