### ISSUE TITLE
Adding large footer using application customizer causing the main content section become small small with vertical scroll bars. 

### ISSUE THREAD

**Issue by dvselva** [SharePoint/sp-dev-fx-extensions#305]
Hello

i added custom footer via application customizer place holders. my footer height is large and it takes up the majority of the content space. i want to footer to be visible when i scroll down the page all the way. this application customizer footer not behaving like out of the box footer.

Here is the screen show how my page looks with custom footer and scroll bar shows up in the content area.

![image](https://user-images.githubusercontent.com/21048891/79769750-83081000-82fa-11ea-87ee-3ea65b5e6f4e.png)

**Comment by hugoabernier** [comment]
Hey @dvselva , you can try to [pre-allocate space](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/preallocated-space-placeholders#defining-pre-allocation-by-using-the-tenant-wide-deployment-option). It may help, but in general there are limitations for the size your headers/footers can take.

See [considerations](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/preallocated-space-placeholders#considerations) in the Microsoft documentation.

**Comment by dvselva** [comment]
Thank you @hugoabernier. this helps with delay in loading the placeholders.  thanks for this as i did not know about this properties. But it did not solve my issue though. i think this placeholder should behave same like out of the box footer and this should start showing up when i go to the end of the page. 

Thanks again for your response.

**Comment by sudharsank** [comment]
@dvselva maybe you can try using the collapse and expand like the same as used in sp-starter-kit, so that it will not occupy much of the main placeholder area by default, if the user want to see the footer, they expand the footer.

**Comment by dvselva** [comment]
Hi @sudharsank , Thanks. ended up doing like it.  but still its not optimal as we need to do one extra click and if it behave  like out of the box footer, it would be ideal.

**Comment by hugoabernier** [comment]
I'm glad you were able to resolve it @dvselva -- although your solution isn't exactly what you wanted.

I'll go ahead and close the issue. If you need anything else, please don't hesitate to open a new issue.

Thanks @sudharsank for your help with this!

**Comment by hugoabernier** [comment]
@dvselva you may want to keep an eye on this Roadmap status: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=61063 to see if/how it will affect footer placeholders in the future.
