### ISSUE TITLE
SPFX Extensions FieldCustomizers onRenderCell not called when navigating

### ISSUE THREAD

**Issue by esutantya** [SharePoint/sp-dev-fx-extensions#56]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

I'm trying out the SPFx Extensions Field Customizer, following this guide https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer

#### Expected or Desired Behavior
Successfully applied the percentage field customizer. when accessing nested item inside folder, the nested item should be rendered correctly, and the breadcrumb should work.

#### Observed Behavior
There are some unexpected behavior when navigating within the document library.
- when accessing nested item inside folder, the field customizer is not rendered
- the root link on document library breadcrumb is not working.

#### Steps to Reproduce

1. Follow the article, deploy the SPFx, and create following structure in the document library
-ROOT
--FolderA
---ItemA1
--ItemB
--ItemC

2. ItemB and ItemC rendered properly
3. Navigate into FolderA, ItemA1 will not rendered properly, I check from console.log, it seems the onRenderCell function still watching the root folder.
4. Use the list breadcrumb, click on Root folder, It will not redirect to root folder, instead will throw console error regarding knockout js and stuck on the folder.
5. refresh the page, and ItemA1 will be rendered correctly, and able to navigate to root folder using the breadcrumb.

#### How to make it work
After the step 3,
- Select the any list item / check the item selector on the left side, the Field Customizer will be rendered.
- Once the field Customizer is rendered, the breadcrumb link will work as well.
- I believe the process should not require me to click on any document in order to make the field Customizer able to work

**Comment by VesaJuvonen** [comment]
Hi @esutantya, could you resubmit this to the sp-dev-docs issue list, which we use for tracking incoming questions and also replicate to our VSO item tracking? - https://github.com/SharePoint/sp-dev-docs/issues. We use that for generic questions and input around the SPFx and are tracking that closely. Other issue lists should only contain potential issues around provided samples in that repository. This will ensure a faster response for your question or feedback. 

I'll close this now, but since this looks like a potential bug, would appreciate if you could resubmit this to the sp-dev-docs issue list for engineering tracking. Thx.

**Comment by esutantya** [comment]
Hi @VesaJuvonen,

Thanks for your reply,
Actually my team has submitted Microsoft support ticket to investigate this and they has fixed it on production as per today.

The issue is related to the dispose object failure within knockout.js. The knockout.js is a symptom. The main issue is related to the react.js failed to unmount Component object lead to object render failure.

They have enhanced the Field Customer rendering as well. We don’t need to click the item to show up the column. It will display automatically and works fine as we expected. Thanks!

**Comment by VesaJuvonen** [comment]
Well - They = our team. Curious on any details around this. Potentially in an email or support ID, so that we ensure that our documentation etc. is also up to date. Would like to understand who from engineering was involved.

**Comment by esutantya** [comment]
Hi  @VesaJuvonen 
they = microsoft support team, the SR number is 117101916521940

**Comment by VesaJuvonen** [comment]
Thx Eric, will have a look to ensure that we are up to date. Meaning of "They = our team" was that if there was actually any changes done in the SPFx side for this, that was done by our engineering team (a team where I'm included). MS support does not apply any changes to the code, that's being done by engineering. Thanks for sharing the SR number, this is enough for me to move forward.
