### ISSUE TITLE
How to localize Command Sets?

### ISSUE THREAD

**Issue by martinlingstuyl** [SharePoint/sp-dev-fx-extensions#59]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Question
How do we localize Command Sets? I noticed there is an **id** property on the items object in the manifest file, which has the following description:

![image](https://user-images.githubusercontent.com/5267487/31431451-12e96100-ae74-11e7-8a6e-e3ca9ccbdc0f.png)

1. If I use the expression as in the screenshot: `"id": "$CommandSetTestCommandSetStrings:CommandSetTestCommandSetStrings.Command1;"` 
2. and add a nl-nl.js file with dutch values.
3. and debug the extension on a dutch site
=> it will load the value from the Command1 property on the localized resource, but only in the default (english) language. 

Is this expected behavior? Should I write the expression differently? Or is it a bug?

Hope someone can shine a light on this!

**Screenshot step 1:**
![image](https://user-images.githubusercontent.com/5267487/31432210-4233b472-ae76-11e7-9762-9893fe71e100.png)

**Screenshot step 2:**
![image](https://user-images.githubusercontent.com/5267487/31431861-25998a2c-ae75-11e7-903e-1d956f777bcb.png)

**Screenshot result:**
![image](https://user-images.githubusercontent.com/5267487/31432153-1a144da8-ae76-11e7-8cb9-5fac55ea34a1.png)

**Comment by martinlingstuyl** [comment]
I dug a little deeper, and it seems this localizing Command Sets in this manner is not yet implemented, or forgotten all about.

In a file named listview-host-assembly-[locale]_[hash].js the commandslist is loaded from the spfx extension manifest.

**While the manifest file neatly contains our localized resources:**
![image](https://user-images.githubusercontent.com/5267487/31437577-089bc668-ae86-11e7-83e2-afc590b306a9.png)

**...the commands list is instantiated with the default property:**
![image](https://user-images.githubusercontent.com/5267487/31437631-35061dc0-ae86-11e7-922c-35825cd27eab.png)

**Comment by martinlingstuyl** [comment]
So basically we're currently stuck with a workaround like this:

```
public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, 'Initialized CommandSetTestCommandSet');

    this.context._commands.forEach((command) => {
      command.title = strings[command.id];
    });

    return Promise.resolve();
  }
```
...which would force us to name resource properties after our command id's (in this case COMMAND_1, COMMAND_2)

**Comment by VesaJuvonen** [comment]
thx Martin, since this is a potential bug in the SPFx, would suggest using Issues list in https://github.com/SharePoint/sp-dev-docs/issues. which is our main channel for getting these kinds of potential issues known... and is getting synced to VSO automatically. I'll close this from here but would suggest to re-open in the right location so it gets the needed attention. I do apologize for the additional work. We use the sp-dev-docs for generic input and other repositories would be good for sample-specific issues, but not really for reporting potential issues in the actual SPFx. Thx for the issue details advance.

**Comment by martinlingstuyl** [comment]
I understand. It began as a question regarding specific extension, so I filed it here. I'll refile it in the correct issues list.

**Comment by martinlingstuyl** [comment]
And there it is, for the sake of progeny: [https://github.com/SharePoint/sp-dev-docs/issues/922](url)
