### ISSUE TITLE
Extension showing when using debug url but not when deployed using .sppkg

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-fx-extensions#63]
#### Category
- [ ] Question
- [ ?] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Hi, Ive built an spfx extension, i started from jquery application toastr to build my code. This was working 👍

Ive tested using the url ?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"a861c815-e425-416d-9520-04bcdf557e27":{"location":"ClientSideExtension.ApplicationCustomizer"}}
and deployed the .sppkg and it worked.

Then I added my code, now i get the following behavior

#### Observed Behavior
Using the debug url, i can see my spfx extension building.

Deployed using the package, i see nothing worrying from the console neither in the UI. How to further troubleshooting ?

I only see : 

- Not one page nav, startPrefetch
- Initialized ClientSideExtensionHelper

#### Steps to Reproduce
I shared my source code https://github.com/seaSide974/spfxmega.
It is a mega menu based on term store (using CSOM), using JQUERY.
Ive added the sppkg, no errors are showing on the app catalog, the feature is correctly on my site collection, i have added the app to the site collection. 
The assets are in : /sites/devjeff/style library/MIS.GlobalNavigation.Modern/deploy/ (file generated from temp/deploy)

Thank you !

**Comment by waldekmastykarz** [comment]
Have you checked the if the browser is loading your new script? You can confirm that using the Network tab of the developer tools in your browser.

**Comment by seaSide974** [comment]
Hi, thanks waldek for your answer.
I dont see them. Could it be due to a wrong url as CDN Path ? Or files not published in my cdn library ? Ill double check

For info, once loaded I shall have a div <div id="megamenu"> loading in the breadcrumb.

**Comment by seaSide974** [comment]
element.xml is missing !

**Comment by waldekmastykarz** [comment]
@seaSide974 great that you could find it. To enable the extension on a site you need either a Feature with element.xml or use remote provisioning such as the PnP Provisioning Engine. Please note also, that using Features doesn't work in combination with tenant-wide deployment.

**Comment by waldekmastykarz** [comment]
If you don't have any further questions please feel free to close this issue 🙂

**Comment by seaSide974** [comment]
Ill try and let you know the outcome, if that is the cause, could 

gulp bundle --ship 
gulp package-solution --ship

Notify such problem ?

By the way it was not here by default when i followed the tutorial from scratch (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint) , neither in the pnp project https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/jquery-application-toastr/sharepoint :(

**Comment by seaSide974** [comment]
I did the modification, it is still not working. 
I pushed my last code in https://github.com/seaSide974/spfxmega/blob/master/sharepoint/assets/elements.xml

**Comment by waldekmastykarz** [comment]
Could be indeed. When you choose to allow tenant-wide deployment when creating the project, the file isn't created

**Comment by waldekmastykarz** [comment]
Could you try creating a new project and see if it's working there? Then you can compare the differences between the two projects to more easily see what's wrong/missing.

**Comment by seaSide974** [comment]
Sure, ill try to set "skipFeatureDeployment": true, too

**Comment by seaSide974** [comment]
I compared and did not find anything wrong. 
Actually i think i never deployed to Office 365 using this solution : https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/jquery-application-toastr/sharepoint

**Comment by seaSide974** [comment]
Ok i solve the issue by : 
1. Create elements.xml
2. Modify the package-solution.json

As specified in this tutorial : https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint

I hope in future, the steps to deploy will be easier and warn in case we missed something ! 

Thank you

**Comment by TaurahSP** [comment]
i still do not see the extension in my list of application to add
