### ISSUE TITLE
Issue in js-application-analytics code while installation

### ISSUE THREAD

**Issue by SumeshKashyap** [SharePoint/sp-dev-fx-extensions#69]
[BUG]

Dear Team,

I am having the unexpected behavior while running npm install command for the solution js-application-analytics. It gives me error 404 not found for a while. I assumed this might be due to old version installed on my laptop but that is also not the case as I updated SharePoint templates.
Other Solutions in the same git repository are working fine for me.
I am attaching the log file and error screen as well
![googleanalyticserrorscreen](https://user-images.githubusercontent.com/19746073/32416272-fc88a574-c246-11e7-98ec-1f93157a9602.JPG)
[2017-11-05T15_22_26_754Z-debug.log](https://github.com/SharePoint/sp-dev-fx-extensions/files/1444170/2017-11-05T15_22_26_754Z-debug.log)

Please let me know if I am doing something wrong.

Thanks and best regards,
Sumesh Kashyap

**Comment by giuleon** [comment]
Hi Sumesh,

Thanks for your feedback, I just tried and everything works fine, no error after the command npm install, please try to delete the solution and re-clone it, after launch **_npm cache clean_** and finally **_npm install_**.

Please let me know.

Kind regards,
Giuliano De Luca

**Comment by SumeshKashyap** [comment]
Thanks Giuliano :)
Unfortunately it did not worked. 
However I tried installing package of microsoft decorator as hinted by error message, it fixed the partial issue but I am still not able to install the solution due to package dependencies, I guess I should follow this [article  ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages )and then come back to you if it does not work. 

Thanks again

**Comment by giuleon** [comment]
you are welcome.

This should solve your issue, in any case let me know.

**Comment by VesaJuvonen** [comment]
Closing as answered.
