### ISSUE TITLE
SPComponentLoader error in SPFx application extension

### ISSUE THREAD

**Issue by mhintner** [SharePoint/sp-dev-fx-extensions#71]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

I'm using SPComponentLoader to load SP.js and other files in a SPFx application extension. This works fine, if the extension is loaded on the start page of a web. But as soon as the extension is loaded on e.g. a document library (/Shared Documents/Forms/AllItems.aspx), the SPComponentLoader produces an unknown error when loading module. 
This is the code  that is supposed to work on every page:

SPComponentLoader.loadScript('/_layouts/15/init.js', {
                globalExportsName: '$_global_init'
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/MicrosoftAjax.js', {
                    globalExportsName: 'Sys'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.Runtime.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.Taxonomy.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.Search.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): void => { 
                //code here
            })
            .catch((reason: any) => {
                //...log error
            });

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#1180

**Comment by VesaJuvonen** [comment]
Moving issue to right repository, since this seems to be a potential generic SPFx bug and not related on any samples in this repository.
