### ISSUE TITLE
Question about extension behavior on modern route change

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/sp-dev-fx-extensions#74]
Hi,
I have interesting use case - I'm using extensions for notifications to show some message to the user which is working fine when I do standard redirect to the page and extension is reloaded, but when I click on the link to redirect to other page in the same site then extension remains and only page content is reloaded which is expected with react (modern) routing, but I would like to call my function on each redirect (even on modern routing). Possibly it is not supported on extensions, but would you think to include such a feature in the future release - I mean some kind a function (e.g. onPageRouteChange) which would be only called in extension on modern routing, but extension would remain as is?

The issue I found is on the root site, e.g. https://tenant.sharepoint.com/SitePages/Home.aspx and then you navigate to SharePoint page (click on the link in suite bar) https://tenant.sharepoint.com/_layouts/15/sharepoint.aspx and click back button on your browser. Extension is not loaded then.

#### Category
- [ x] Question / Suggestion
- [ x] Issue

Thanks 
Saulius

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#1181

**Comment by VesaJuvonen** [comment]
Moving issue to right repository, since this seems to be a potential generic SPFx bug and not related on any samples in this repository.
