### ISSUE TITLE
Field Customizer isn't initialized on new rows in a Document Library (possible other list types also)

### ISSUE THREAD

**Issue by Megamannen** [SharePoint/sp-dev-fx-extensions#76]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When uploading a new file to a Document Librarary that uses SPFX Field Customizer Extension we expect the new item to also get the Field Customizer and that they are initialized.

#### Observed Behavior
Right now the default behaviour of the column is removed but the Field Customizer isn't added

#### Steps to Reproduce
1. Have a Document Library with some files and use a field customizer on a column.
2. Upload a new item
3. Observe

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#1179

**Comment by VesaJuvonen** [comment]
Moving issue to right repository, since this seems to be a potential generic SPFx bug and not related on any samples in this repository.
