### ISSUE TITLE
Tenant Global NavBar Application Customizer > Deployment > TenantGlobalNavBarProvisionCustomizer.ps1

### ISSUE THREAD

**Issue by jykoning** [SharePoint/sp-dev-fx-extensions#77]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior
Simple addition: I was searching for a way to remove the application customizer once deployed with PS, this can be done via:
$context = Get-PnPContext
$web = Get-PnPWeb
$context.Load($web)
Execute-PnPQuery
$web.UserCustomActions.Clear()
$context.Load($web.UserCustomActions)
Execute-PnPQuery

Also needed when running deploy more than once because it will load the customizer two times. 

#### Observed Behavior
Run twice or try to delete the customizer

#### Steps to Reproduce
Tenant Global NavBar Application Customizer > Deployment
> TenantGlobalNavBarProvisionCustomizer.ps1
Run twice or try to delete the customizer

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
thx Jan-Ype for sharing. I'll close this issue though as it's not really an issue or anything we can act on.
