### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by GwSoJ** [SharePoint/sp-dev-fx-extensions#91]
Sample: Global Navbar.
Sorry but this doesn't deploy like any other extension I've used. I've copied over the files and published the package all successfully but adding the app to any site does nothing. It works perfectly in debug mode. What am I missing? Incidentally the ps1 script doesn't work either.

#### Category
- [ ] Bug

#### Expected or Desired Behavior
Same as debug mode

#### Observed Behavior
Nothing, no errors just nothing.

#### Steps to Reproduce
build and package solution in --ship
copy files to cdn
publish package
add app to modern site

Thanks.

**Comment by KrisJanssen** [comment]
I have recently picked up this repo to get acquainted with SPFx development.

Using another example in the set,[ js-field-weather](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/js-field-weather), I encountered what I think are similar issues to yours.

There seem to be distinct differences between SP2016 and SP Online in terms of required versions for dependencies, as outlined [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages).

I was testing the mentioned extension on a list in SP Online and got the same behaviour as you: nothing would actually happen. That was until I noticed an unhandled exception in console suggesting that a wrong type was supplied somewhere.

I proceeded to update al '@microsoft/...' dependencies as per the linked page, followed by 'gulp clean' and after that, things started working as expected.

Hope this helps...

**Comment by GwSoJ** [comment]
Hi Kris,

Thanks for the mail and the suggestion. Unfortunately I've tried all of that and I get no error on the console. There never was an error in my package. All my packages are up to date and current. Not sure where to go with it now to be honest.

Gw.
