### ISSUE TITLE
Security Trimming for the react-application-tenant-global-navbar SPFx menu

### ISSUE THREAD

**Issue by devfunda3** [SharePoint/sp-dev-fx-extensions#96]
#### Category
- [x] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior
I am using the https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-application-tenant-global-navbar extension in the production environment and it is working really well. So a big thank you first for the extension code.
It would be great if the menus are security trimmed similar to managed metadata navigation with friendly urls, which will only show menus if the user has access to the page the menu links to.

#### Observed Behavior
Currently, the menu from the term store is not security trimmed. Users will see the menu and if they click on a menu, which links to a page they don't have access to, it takes them to an access denied page. It would have been great to not show the menu at all.

#### Steps to Reproduce
Set up as detailed in the Readme and set a few of the menu terms to pages the user does not have access to.

Thanks for your contribution! Sharing is caring.

**Comment by devfunda3** [comment]
I asked this question at yesterday's MS Tech Summit in Birmingham and a SharePoint specialist said it would be best to reach out to @VesaJuvonen to get a quick reply - so here goes.

**Comment by thsdev** [comment]
Any guidance or solution as to security trimming the navigation elements in the react-application-tenant-global-navbar SPFx project?

**Comment by PooLP** [comment]
Same interrogation for me, and any idea for a real "selected" state for current page.

**Comment by jtcooper1224** [comment]
Using SPFx App Customizer I'm using a _fetchFromSPList() call to populate a MegaMenu (MM) from a SharePoint list onto modern pages. Site Owner permissions can see the MM from any modern page, list, or library, so no problem there, but users with Member (contribute) permissions and Visitor (read-only) can not see the MM on modern pages, but can see the MM list in Site Contents. 

I created a new permission level and assign it to a test user aiming for only Read access to the MM list. But specifically, the "Manage Lists" checkbox must be selected for this user to see the MM on modern pages.

Within the user's permission level, I've cut off most everything including Add, Edit, and Delete Items, so when visiting the list in Site Contents the user can see the items without editing them, but the 'Manage Lists" permissions gives the user access to the MM List Settings, with access to create new columns and even delete the list.

Why would a user need Manage List permissions to view a SPFx application customizer? 

Troubleshooting Ideas:
On MS docs: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint I've tried placing the <AppPermissionRequests> elements in for scoping rights to the specific web and the specific list, but all of the documentation points to an AppManifest.xml file, which does not exist in my SPFx solution. 

The most similar file in my solution is the package-solution.json file which states the package version and just so happens to have a "webApiPermissionRequests" attribute, but intelecense gives me no options to scope the permissions specifically. Anyone have examples to target my specific list with a permission level to Read access without List Management permission?

Another suspicion is in the Node Modules > sp-pnp-js > lib > sharepoint > lists.d.ts file there's a  ListEnsureResult boolean that being used when I call for my list data using _fetchFromSPList(). I suspect there could be something here that's relying on a permission level not given to all users.

**Comment by jtcooper1224** [comment]
I have found the resolution.

In my request for the SharePoint list I was using an .ensure() function - 

web.lists.ensure("MegaMenu")

... and to use this call I had to ensure that the list existed to bring back the data. The problem was that the code reads "ensure" as "go find all of the SharePoint lists and make sure this one exists, then give me it's data. The "Read" permissions users do not have access to do this with just read permission. So I changed the code to "web.lists.getByTitle("MegaMenu")" which will assume that one exists.

Resolved my issue. Thanks,

**Comment by jonasesser** [comment]
Just three other thoughts:

1. Security trimming by search

Create a navigation menue by searching for sites / items or folders. The sites must be marked with some metadata information (e.g. TopNavigation, Submenue1 or so). 

2. Security trimming by item level security

Create a central List with a hierarchical structure (e.g with folders) which reflects the navigation structure. Also title, description and pictures could be saved there. Then break the permission heredity where necessary. Assign permissions to navigation items by using ad groups / office group / what ever.

3. Security trimming by url check (possible but probably not a good idea)

Extend the react-application-tenant-global-navbar solution with a url checker. Check each linked url in the background by making a ajax call. If it's failed, grey out or hide the menue link. This must be done in the background and maybe the result could saved in the local storage to be less expensiv for all further requests.

What do you think?
