### ISSUE TITLE
Unable to delete app from site recycle bin

### ISSUE THREAD

**Issue by bubbleswap** [SharePoint/sp-dev-fx-extensions#99]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Observed Behavior
When a spfx extension app is deleted, it goes to the recycle bin (with 0 kb). I'd go to the recycle bin to delete the extension app again, and would receive this error message:

> Sorry, something went wrong
> An unexpected error has occurred.
> TECHNICAL DETAILS
> Troubleshoot issues with Microsoft SharePoint Foundation.
> Correlation ID: c492469e-60a1-5000-1cdd-86f5344ecc11

This happens on multiple site collections, as well as with **spfx web part app**. 

After an app is deleted, when I re-add the app (usually with an updated version number if there's modification), I could get one of these two responses (the screen cap is what's happening at the same time):

1. 
![image](https://user-images.githubusercontent.com/27218932/35739233-f91e6934-07fe-11e8-87bc-3849835b9c46.png)

2. 
> Sorry, something went wrong
> A different version of this App is already installed with the same version number.  You need to delete the app from the site and the site recycle bin to install this version.
> TECHNICAL DETAILS
> Troubleshoot issues with Microsoft SharePoint Foundation.
> Correlation ID: 3e93469e-e044-5000-e9c5-ad565dc578d6

I'm not sure if this is preventing me from re-installing an updated app, or if it's constantly restoring, but the version number from newer pkkg does show when an app is re-added.

**Also having [this issue 775 with web part app](https://github.com/SharePoint/sp-dev-docs/issues/775) showing in some site toolbox gallery but not others, it's why I'm deleting apps and re-adding them, per recommendation as a fix.

**Comment by bubbleswap** [comment]
I can delete web part and extension apps from recycle bin now...and the fix? ***pulls hair***

**Use modern recycle bin.** 

But there's a catch, if the app was deleted in classic mode (which SPO only allows apps to be deleted in classic mode), and you then go to the recycle bin, the recycle bin is also in classic mode. _There's no "exit classic experience" in recycle bin_ either.
![image](https://user-images.githubusercontent.com/27218932/35750695-d5b829b0-0823-11e8-8faf-b2a9a1199e34.png)

I had to make sure when the app is deleted from classic 'site contents' that I return to modern mode, then go to recycle bin. (Though in modern recycle bin, there's a link to "Return to classic"
![image](https://user-images.githubusercontent.com/27218932/35750764-17c6ff8e-0824-11e8-8a54-edc3624b4953.png)

This made me feel a little crazy....is this common knowledge or am I learning the hard way?

**Comment by roncourville** [comment]
That's a pretty creative resolution there!

I'm facing the same issue currently but haven't got the modern layouts enabled for the current site. Has anyone found an alternative fix for this?

**Comment by roncourville** [comment]
I was eventually able to find a solution on my end as well. Turns out that if you go to the site collection level recycle bin, then the app package file appears there, and I WAS able to delete from there. I believe that I still did get an error message on deleting from the site collection level, but the actual deletion action from the recycle bin did work anyway.

After I was able to successfully delete, I could finally clear up the issue mentioned at...
https://github.com/SharePoint/sp-dev-docs/issues/775

**Comment by shaipetel** [comment]
5 months later, still no fix for this...

Thanks for sharing - I was having the same problem, saved me some time...

**Comment by gilroitto** [comment]
Thank you! This saved me!
Why is the issue closed? The issue remains.

**Comment by shaipetel** [comment]
@gilroitto the issue is closed since the original poster found a workaround and closed it.

I agree, this should still be active and fixed but only the original poster or the team can reopen it...

**Comment by gschwendt** [comment]
@VesaJuvonen can this be reopened? I faced this same issue today as well. Work-around was to delete it from the Site Collection Recycle Bin.

**Comment by TowersOfHinoi** [comment]
For future reference: accessing second stage recycle bin and clearing all related content to the app also solves this.

**Comment by eschrader** [comment]
If you go to the Recycle Bin, click the link in the bottom left called "go to second stage recycle bin", which will take you to /_layouts/15/AdminRecycleBin.aspx?view=13 where you can FINALLY delete your app. Going to Site Collection Settings > Recycle Bin is not the same as the above URL for some reason, even though both are modern.

**Comment by vikramsamal** [comment]
Believe it or not if you delete everything from Recycle Bin then the deletion is happening.

**Comment by SlippyDong** [comment]
I installed and deleted the same app several times in a site and then went to delete them from the recycle bin. Worked fine for first stage recycle bin but it's impossible to delete any of them from second stage recycle bin. Either one by one or by emptying the bin.
